# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1apVuRvtwsJICj-K6qkmm4IYKIzusf-rG
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv(r'1) iris.csv')

df.head(10)

df.tail(5)

df.info()

df.describe()

df.isnull().sum()

df['species'].value_counts()

df.hist(color="blue",edgecolor="black",figsize=(10,6))
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,6))
sns.boxplot(data=df)
plt.show()

plt.figure(figsize=(10,6))
sns.pairplot(df,hue="species")
plt.show()

plt.figure(figsize=(8, 6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.show()

plt.figure(figsize=(8, 5))
sns.scatterplot(data=df,x='sepal_length', y='petal_length',hue='species')
plt.show()

plt.pie(df['species'].value_counts(),labels=df['species'].unique(),autopct='%1.1f%%')
plt.show()